server:
  port: 8095  # 端口号

spring:
  application:
    name: client-scholar
  jackson:
    default-property-inclusion: non_null
  redis:
    password: redis-academic-2021  # Redis 密码
    timeout: 5000
    cluster:
      nodes:  # Redis 集群地址（可更换为单节点）
        - 192.168.0.228:7001
        - 192.168.0.228:7002
        - 192.168.0.228:7003
        - 192.168.0.239:7001
        - 192.168.0.239:7002
        - 192.168.0.239:7003
      max-redirects: 3
    jedis:
      pool:
        max-idle: 10
        max-wait: -1ms
        min-idle: 2
  elasticsearch:
    rest:
      username: elastic  # Elasticsearch 用户名
      password: elastic-academic-2021  # Elasticsearch 密码
      uris: http://192.168.0.239:9200  # Elasticsearch IP 地址与端口号

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka-academic-2021@192.168.0.228:8100/eureka/  # Eureka 地址

knife4j:
  basic:
    enable: true
    username: knife4j
    password: knife4j-academic-2021
  enable: true

logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: warn
    com.netflix.discovery.DiscoveryClient: warn
