server:
  port: 8090

eureka:
  server:
    username: eureka
    password: 114514
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.username}:${eureka.server.password}@localhost:8100/eureka/

spring:
  application:
    name: client-gateway
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 114514
    timeout: 1500
    jedis:
      pool:
        max-idle: 10
        max-wait: -1ms
        min-idle: 2
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://10.135.37.106
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
      routes:
        - id: 搜索服务
          uri: lb://client-search
          order: 1
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix=1
        - id: 账号服务
          uri: lb://client-account
          order: 2
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1

logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: warn
