server:
  port: 8090

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka-academic-2021@localhost:8100/eureka/

spring:
  application:
    name: client-gateway
  redis:
    password: 114514
    timeout: 5000
    jedis:
      pool:
        max-idle: 10
        max-wait: -1ms
        min-idle: 2
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: 搜索服务
          uri: lb://client-search
          order: 1
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix=1
        - id: 账号服务
          uri: lb://client-account
          order: 2
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1

logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: warn
