server:
  port: 8090

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka-academic-2021@192.168.0.228:8100/eureka/

spring:
  application:
    name: client-gateway
  redis:
    password: redis-academic-2021
    timeout: 5000
    cluster:
      nodes:
        - 192.168.0.228:7001
        - 192.168.0.228:7002
        - 192.168.0.228:7003
        - 192.168.0.239:7001
        - 192.168.0.239:7002
        - 192.168.0.239:7003
      max-redirects: 3
    jedis:
      pool:
        max-idle: 10
        max-wait: -1ms
        min-idle: 2
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:8080
              - http://121.36.98.60
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods: "*"
      routes:
        - id: 搜索服务
          uri: lb://client-search
          order: 1
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix=1
        - id: 账号服务
          uri: lb://client-account
          order: 2
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1
        - id: 后台服务
          uri: lb://client-admin
          order: 6
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: warn

auth:
  max-inactive-interval: 86400

admin:
  username: admin
  password: admin-academic-2021
