server:
  port: 8090  # 端口号

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka-academic-2021@192.168.0.228:8100/eureka/  # Eureka 地址

spring:
  application:
    name: client-gateway
  redis:
    password: redis-academic-2021  # Redis 密码
    timeout: 5000
    cluster:
      nodes:  # Redis 集群地址（可更换为单节点）
        - 192.168.0.228:7001
        - 192.168.0.228:7002
        - 192.168.0.228:7003
        - 192.168.0.239:7001
        - 192.168.0.239:7002
        - 192.168.0.239:7003
      max-redirects: 3
    jedis:
      pool:
        max-idle: 10
        max-wait: -1ms
        min-idle: 2
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:  # 跨域配置
              - http://localhost:8080
              - http://localhost:8081
              - http://121.36.98.60
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods: "*"
      routes:
        - id: 搜索服务
          uri: lb://client-search
          order: 1
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix=1
        - id: 账号服务
          uri: lb://client-account
          order: 2
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1
        - id: 分析服务
          uri: lb://client-analysis
          order: 3
          predicates:
            - Path=/analysis/**
          filters:
            - StripPrefix=1
        - id: 学者服务
          uri: lb://client-scholar
          order: 4
          predicates:
            - Path=/scholar/**
          filters:
            - StripPrefix=1
        - id: 后台服务
          uri: lb://client-admin
          order: 5
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: 资源服务
          uri: lb://client-resource
          order: 6
          predicates:
            - Path=/resource/**
          filters:
            - StripPrefix=1

logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: warn

auth:
  max-inactive-interval: 86400  #  用户登录状态无操作过期时限，默认为 24 小时，单位：秒

admin:
  username: admin  # 管理员用户名
  password: admin-academic-2021  # 管理员密码
