mode: deploy  # test / deploy

settings:
  test:
    host: localhost
    register: false
  deploy:
    host: localhost
    register: true

server:
  port: 8092

spring:
  application:
    name: client-account
  redis:
    database: 0
    host: ${settings.${mode}.host}
    port: 6379
    password: 114514
    timeout: 1500
    jedis:
      pool:
        max-idle: 10
        max-wait: -1ms
        min-idle: 2
  elasticsearch:
    rest:
      username: elastic
      password: 114514
      uris: http://${settings.${mode}.host}:9200
  mail:
    host: smtp.163.com
    username: ruangong202105@163.com
    password: NYTIRYOWHUTHAPIS
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
        debug: false
    protocol: smtp
    port: 587

eureka:
  server:
    username: eureka
    password: 114514
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.username}:${eureka.server.password}@${settings.${mode}.host}:8100/eureka/
    register-with-eureka: ${settings.${mode}.register}

knife4j:
  basic:
    enable: true
    username: knife4j
    password: 114514
  enable: true
